// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VR.Migrations
{
    [DbContext(typeof(VRDbContext))]
    [Migration("20250411103708_AddBoxesTable")]
    partial class AddBoxesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VR.Models.Box", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<string>("SupplierIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identifier");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("VR.Models.Box+Content", b =>
                {
                    b.Property<string>("PoNumber")
                        .HasColumnType("text");

                    b.Property<string>("Isbn")
                        .HasColumnType("text");

                    b.Property<string>("BoxIdentifier")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PoNumber", "Isbn");

                    b.HasIndex("BoxIdentifier");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("VR.Models.Box+Content", b =>
                {
                    b.HasOne("VR.Models.Box", null)
                        .WithMany("Contents")
                        .HasForeignKey("BoxIdentifier");
                });

            modelBuilder.Entity("VR.Models.Box", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
